### ISSUE TITLE
Exclude unsupported chars from resourceDocument

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#25]
A layer to exclude unsupported chars contained in the Resource properties. It's need a one-to-one corrispondation from Resource to documentResource

**Comment by alelb** [comment]
No longer need to implement it.

**Comment by alelb** [comment]
`$` char it's not a valid char for mongoDB.

**Comment by leogr** [comment]
Do you mean char escaping?

**Comment by alelb** [comment]
Key escaping done (f096afc5e4b920e58d30022f1993425ddd1af085). I'll close the issue.
