### ISSUE TITLE
Storage methods testing

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#26]

**Comment by leodido** [comment]
Hey @alelb, @skryja & @samechelon are completing them.

Guys please update us soon!
:1st_place_medal:

**Comment by leogr** [comment]
Wait for #42 pls! It's coming soon 🔊

**Comment by leogr** [comment]
Refs #43

**Comment by leogr** [comment]
cc @alelb @samechelon https://github.com/fabbricadigitale/scimd/commit/e78565c7bbaa53846bc5cce99d9bdd215a97ea2a should fix the issue related to `Find()`. Could you double check, pls?

**Comment by leodido** [comment]
:flight_departure:

**Comment by alelb** [comment]
Now it works.
I'll close the issue.
