### ISSUE TITLE
ABNF rules and case insensitivity of attribute names 

### ISSUE THREAD

**Issue by leogr** [fabbricadigitale/scimd#3]
As per https://tools.ietf.org/html/rfc7643#section-2.1, attribute names MUST conform to the following ABNF rules:
```
               ATTRNAME   = ALPHA *(nameChar)
               nameChar   = "$" / "-" / "_" / DIGIT / ALPHA
```

Furthermore, ABNF strings are **case insensitive**  so all attribute names should be case insensitive too, but it's difficult to achieve because implementation should:

- [x] Validate the attr name by the above ABNF rules (eg. within `schemas.core.Attribute`)
- [x] Also accepting a case-insensitive match when unmarshalling
- [x] Ensure that no naming collision occurs with the same set of attrs (eg. `fooBaz` and `foobaz`)
- [x] Querying by path should consider case insensitivity
...other?

<s>Maybe wont'fix?</s>

**Comment by leogr** [comment]
I've documented [rules](https://github.com/fabbricadigitale/scimd/commit/ac72003311111da4da173c8d158ad1bcb213db54) which could be implemented easily.

@leodido we should avoid naming collision as described above. Validation should able to accomplish that, do you agree?

**Comment by leogr** [comment]
By https://github.com/fabbricadigitale/scimd/commit/62b7a325fe571ee012972a39bd8b6291744b38aa `filter` accepts case-insensitive match for attribute path, also it's able to normalise them in respect of the given resource type.

**Comment by leogr** [comment]
In order to close this issue, we have to accomplish last task:  for each attribute set,  the attribute's `Name` must be unique (using a case insensitive comparison), ensuring that no naming collision occurs.

Currently we have the following sets:
- `Attributes` property of `core.Schema`
- `SubAttributes` property of `core.Attributes`

@alelb @samechelon Could you fix that?

**Comment by alelb** [comment]
@samechelon does that [ref](7e480df34a1b681c698a61be44806e590fd677b5).
I'll close the issue.
