### ISSUE TITLE
Validator to check mutability/returned values

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#45]
This validator checks that if an attribute with a mutability of "writeOnly" has a returned setting of "never" ([rfc7643](https://tools.ietf.org/html/rfc7643#section-7)).

**Comment by leodido** [comment]
Please explain better.

**Comment by leodido** [comment]
Try to use isField cross-field custom validator.

**Comment by alelb** [comment]
No need to implement that as @leogr commented in #7. So I'll close this issue.
