### ISSUE TITLE
Review data types API

### ISSUE THREAD

**Issue by leodido** [fabbricadigitale/scimd#5]
I propose to rename `IsAssigned`.

We should also rename `IsMultiValued` into `IsMultiValue` since the complementar method is `IsSingular`.

**Comment by leogr** [comment]
I agree. As per https://tools.ietf.org/html/rfc7643#section-2.4, it's defined "Multi-Valued“ for attributes. In this case code is checking against a value, so funcs could be renamed to:

- `IsSingleValue` checks that is a single value (so it can be hold by a `Singular Attribute`
- `IsMultiValue` checks that is a slice of values (so it can be hold by a `Multi-Valued Attribute`
