### ISSUE TITLE
Subattributes of a complex excludedAttribute aren't excluded 

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#51]
Because the attributes are flattened the subattributes of a complex excludedAttribute cannot be differentiated, so they remain in the resulting set ([ref](https://github.com/fabbricadigitale/scimd/blob/develop/api/attr/projection.go#L62)).

`GET \v2\User\...excludedAttributes=urn:something:User:name`

**included/default attributes**
`urn:something:User:name`
`urn:something:User:name.familyName`
`urn:something:User:email.value`

**excluded attributes**
`urn:something:User:name`

**resulting set** = **included/default attributes** - **excluded attributes**
`urn:something:User:name.familyName`
`urn:something:User:email.value`

**Comment by leogr** [comment]
By 613f229 this issue cannot be fixed as described above.

cc @leodido @alelb @samechelon won't fix?

**Comment by leodido** [comment]
To me we can leave it as is now - ie., not supporting the exclusion of entire complex attributes.

For future reference.

We should use a TreeMap data structure defining the ordering with want through a comparator.

Thus assuring that, when a complex attribute (the _parent_) is specified it will always be in a previous position with respect to their _children_.

This way mongo projection and so its results will be predicatable.

**Comment by leodido** [comment]
Postponing to a future release.
