### ISSUE TITLE
Excluding attribute's sub-attribute will exclude every sub-attribute of that attribute

### ISSUE THREAD

**Issue by samechelon** [fabbricadigitale/scimd#52]
Excluding an attribute's subattribute will exclude every other subattribute of that attribute

eg., [HERE](https://github.com/fabbricadigitale/scimd/blob/3e9684532b32ba523cb259d003408a310f304d67/internal/test/integration/query_resource_test.go#L55-L64)

**TEST RESULT**
The test's result in this case will be positive, so it will pass, even though should be negative, it shouldn't pass, because the excluded `subattribute` is `urn:ietf:params:scim:schemas:core:2.0:User:emails.value`, while making a check on another `subattribute` of `email` that should be present among the `email` `attribute`'s `subattributes`.

**Comment by leogr** [comment]
I've just fixed the test. This issue should be fixed (if so, close it).
Also, I commented the test before because #51 is still present

**Comment by samechelon** [comment]
:+1:
