### ISSUE TITLE
Create successfully calls don't return the newly created resource

### ISSUE THREAD

**Issue by alelb** [fabbricadigitale/scimd#59]
When a new resource is created, an HTTP response is returned with HTTP status code 201 (Created). There isn't the newly created resource in the body of the response. 

We want to fix that? @leodido @samechelon @leogr

**Comment by leodido** [comment]
What RFC mandates?

**Comment by alelb** [comment]
Here's a [reference](https://tools.ietf.org/html/rfc7644#section-3.3) about resource creating.

Same question about replacing with PUT response. Here's a [ref](https://tools.ietf.org/html/rfc7644#section-3.5.1) about update with PUT.

**Comment by alelb** [comment]
Same question about update resource...

**Comment by alelb** [comment]
It's a good flow choise to return always the resource created/updated. 

Do we have to reload resource at api or storage level? @leodido

**Comment by leogr** [comment]
```
When the service provider successfully creates the new resource, an
   HTTP response SHALL be returned with HTTP status code 201 (Created).
   The response body SHOULD contain the service provider's
   representation of the newly created resource.
```
I suggest to fetch the resource after its insertion [here](https://github.com/fabbricadigitale/scimd/blob/6451191415bd9e4683a5e6ede4b08077d1c97127/api/create/resource.go#L54), then it can be returned within the response's body.

**Comment by alelb** [comment]
:+1:
