### ISSUE TITLE
Giving an empty ResourceType to Contexts()

### ISSUE THREAD

**Issue by samechelon** [fabbricadigitale/scimd#63]
If an empty `ResourceType` is passed to the `Contexts()` method will panic [here](https://github.com/fabbricadigitale/scimd/blob/feature/server/schemas/core/resource_type.go#L58)

What to do if an empty `ResourceType` somehow is passed to this method?

**Comment by leogr** [comment]
It's ok to panic when a schema is missing from the repository. It just notices you that the service provider was misconfigured. 
API's users must ensure that definitions (schemas, resource types, and configs) have been loaded prior to use them.

@leodido do you agree?

**Comment by leodido** [comment]
Yes I agree.
